trainer: "mdm"
dataset: "bracket"
model:
  hidden_size: 256
  n_heads: 4
  cond_dim: 64
  dropout: 0.1
  n_blocks: 4
interpolant:
  type: "mdm"
  max_length: 64
  tokens: 4
  mask_token: 0
  pad_token: 3
  unmask_schedule:
    type: "linear"
training:
  batch_size: 2
  per_gpu_batch_size: 2
  learning_rate: 0.0001
  devices: 1
  nodes: 1
  cpus: 1
  weight_decay: 0.01
  max_steps: null
  num_epochs: 100
  checkpoint_dir: "/n/netscratch/albergo_lab/Lab/brianlck/interpretable-flow/checkpoints/bracket/mdm"
  save_top_k: 1
  save_every_n_epochs: 1
  warmup_steps: 1000
  ema_decay: 0.9999
  filter_max_length: false
wandb:
  entity: "jaeyeon_kim-harvard-university"
  project: "interpretable-flow"
  name: "mdm-any-order"
