# This file is currently unusable in the current version
trainer: "semiautoregressive"
dataset: "bracket"
model:
  hidden_size: 256
  n_heads: 4
  cond_dim: 64
  dropout: 0.1
  n_blocks: 4
interpolant:
  type: "semi-auto"
  max_length: 64
  tokens: 4
  mask_token: 0
  pad_token: 3
  mask_schedule:
    type: "geometric"
    min: 5
    max: 0.01
training:
  batch_size: 32
  learning_rate: 0.0001
  devices: 1
  num_epochs: 100
  checkpoint_dir: "checkpoints/bracket/semi-auto"
  save_top_k: 3
  save_every_n_epochs: 5